const urlImage = "https://lh3.googleusercontent.com/d/";

export const data = [
  {
    id: 1,
    nombre: "Tinto",
    descripcion: "Café negro fuerte y aromático.",
    precio: 2.5,
    categoria: "Bebidas calientes",
    disponible: true,
    imagen: urlImage + "14GPOvb8Ez0ZexwXdZOmkLUCqYtkoF0fg",
  },
  {
    id: 2,
    nombre: "Capuchino",
    descripcion: "Café espresso con leche vaporizada y espuma de leche.",
    precio: 3.0,
    categoria: "Bebidas calientes",
    disponible: true,
    imagen: urlImage + "1-8QPJ4ABkZp8jnYfzyB6BJrtd7FqTt69",
  },
  {
    id: 3,
    nombre: "Perico",
    descripcion: "Té verde natural con un toque de miel.",
    precio: 2.0,
    categoria: "Bebidas calientes",
    disponible: true,
    imagen: urlImage + "1NxyQ1rtRY-iYkBFn3NYpkauIqY2yODIl",
  },
  {
    id: 4,
    nombre: "Frapuchino",
    descripcion: "Crujiente croissant de mantequilla.",
    precio: 1.8,
    categoria: "Repostería",
    disponible: true,
    imagen: urlImage + "18W6QF_ZBEM_sozhPtQxPGijeRQBY5GEG",
  },
  {
    id: 5,
    nombre: "Frape de milo",
    descripcion: "Sandwich fresco con jamón, queso y vegetales.",
    precio: 4.5,
    categoria: "Comida",
    disponible: true,
    imagen: urlImage + "1kmQ86XT7j4vx33g-l7A7nN83ZuKLeSYs",
  },
  {
    id: 6,
    nombre: "Frape de oreo",
    descripcion: "Jugo recién exprimido de naranjas frescas.",
    precio: 3.5,
    categoria: "Bebidas frías",
    disponible: false,
    imagen: urlImage + "1sr1YDv1ZQ2YY4gq4CNiFPDr3YAwZCBMx",
  },
  {
    id: 7,
    nombre: "Milo",
    descripcion: "Brownie casero con trozos de chocolate",
    precio: 2.2,
    categoria: "Repostería",
    disponible: true,
    imagen: urlImage + "1n1i_RNDqPJaOogLbmTsSf5BclMsLDwHq",
  },
  {
    id: 8,
    nombre: "Aromatica",
    descripcion: "Botella de agua mineral sin gas.",
    precio: 1.0,
    categoria: "Bebidas frías",
    disponible: true,
    imagen: urlImage + "12vsO1nkYi98xdgNWm_6Jsikgce5vRKbf",
  },
  {
    id: 9,
    nombre: "Vaso de leche",
    descripcion: "Botella de agua mineral sin gas.",
    precio: 1.0,
    categoria: "Bebidas frías",
    disponible: true,
    imagen: urlImage + "1gW-sYLCfjfYWjuRQEeAnL__X-7dfviqj",
  },
];
